<?php

/**
 * PluginpeanutActuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginpeanutActuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginpeanutActuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginpeanutActu');
    }
}