<?php

/**
 * PluginpeanutActu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    peanutActu
 * @subpackage model
 * @author     Alexandre 'pocky' Balmes <albalmes@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginpeanutActu extends BasepeanutActu
{
  public function changeStatus()
  {
    if('draft' == $this->getStatus())
    {
      $this->setStatus('publish');
    }
    elseif('publish' == $this->getStatus())
    {
      $this->setStatus('draft');
    }
    
    $this->save();
  }
}