peanutActu:
  actAs:
    Timestampable: ~
    Sluggable:
      fields:      [title]
    Seoable:       ~
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true   
    title:
      type: string(255)
      notnull: true
    content:
      type: clob
    excerpt:
      type: clob
    author:
      type: integer
      notnull: true
    status:
      type: enum
      values: [draft, publish]
      default: draft
  relations:
    sfGuardUser:
      local: author
      foreign: id
